### ISSUE TITLE
求quark-n可以用的openwrt固件

### ISSUE THREAD

**Issue by kingo132** [peng-zhihui/Project-Quantum#23]
我在seeed店铺买的成品quark-n，cpu是h3的那个。
我尝试了openwrt官方的OrangePi PC (H3)、BananaPi M2、Orange Pi Plus (H3)固件，都无法启动。
自己按照硬件参数编译了三四次，也没有成功。
求作者出个openwrt固件，或者编译openwrt的参数配置。
希望可以支持openwrt，希望quark-n越来越好，谢谢作者。

**Comment by peng-zhihui** [comment]
理论上是可以的啊，你确定设备树配置正确，串口中终端设置是uart应该就可以启动的

发送自 Windows 10 版邮件应用

发件人: kingo
发送时间: 2021年2月17日 上午 11:01
收件人: peng-zhihui/Project-Quantum
抄送: Subscribed
主题: [peng-zhihui/Project-Quantum] 求quark-n可以用的openwrt固件 (#23)

我尝试了openwrt官方的OrangePi PC (H3)、BananaPi M2、Orange Pi Plus (H3)固件，都无法启动。
自己按照硬件参数编译了三四次，也没有成功。
求作者出个openwrt固件，或者编译openwrt的参数配置。
希望可以支持openwrt，希望quark-n越来越好，谢谢作者。

**Comment by kingo132** [comment]
> 理论上是可以的啊，你确定设备树配置正确，串口中终端设置是uart应该就可以启动的 发送自 Windows 10 版邮件应用 发件人: kingo 发送时间: 2021年2月17日 上午 11:01 收件人: peng-zhihui/Project-Quantum 抄送: Subscribed 主题: [peng-zhihui/Project-Quantum] 求quark-n可以用的openwrt固件 (#23) 我尝试了openwrt官方的OrangePi PC (H3)、BananaPi M2、Orange Pi Plus (H3)固件，都无法启动。 自己按照硬件参数编译了三四次，也没有成功。 求作者出个openwrt固件，或者编译openwrt的参数配置。 希望可以支持openwrt，希望quark-n越来越好，谢谢作者。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我是按照这个教程编译的：https://github.com/coolsnowwolf/lede
编译的时候可以选择全志h3的cpu，但是里面选择设备的时候，只有OrangePi PC (H3)、BananaPi M2、Orange Pi Plus (H3)这3个设备是全志h3的，我把3个设备全部编译了一遍，都无法启动
我有点搞不太懂设备树要怎么添加，我看了一篇文章说好想要修改openwrt内核，不知道是不是这样子？
https://openwrt.org/docs/guide-developer/adding_new_device
但是内核修改我没弄过，估计很难。

**Comment by peng-zhihui** [comment]
参考这个NanoPi NEO/zh - FriendlyARM WiKi
不过需要自己添加rtl8723的驱动才能使用板载的wifi蓝牙模块

发送自 Windows 10 版邮件应用

发件人: kingo
发送时间: 2021年2月17日 下午 5:33
收件人: peng-zhihui/Project-Quantum
抄送: 稚晖; Comment
主题: Re: [peng-zhihui/Project-Quantum] 求quark-n可以用的openwrt固件 (#23)

理论上是可以的啊，你确定设备树配置正确，串口中终端设置是uart应该就可以启动的 发送自 Windows 10 版邮件应用 发件人: kingo 发送时间: 2021年2月17日 上午 11:01 收件人: peng-zhihui/Project-Quantum 抄送: Subscribed 主题: [peng-zhihui/Project-Quantum] 求quark-n可以用的openwrt固件 (#23) 我尝试了openwrt官方的OrangePi PC (H3)、BananaPi M2、Orange Pi Plus (H3)固件，都无法启动。 自己按照硬件参数编译了三四次，也没有成功。 求作者出个openwrt固件，或者编译openwrt的参数配置。 希望可以支持openwrt，希望quark-n越来越好，谢谢作者。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
我是按照这个教程编译的：https://github.com/coolsnowwolf/lede
编译的时候可以选择全志h3的cpu，但是里面选择设备的时候，只有OrangePi PC (H3)、BananaPi M2、Orange Pi Plus (H3)这3个设备是全志h3的，我把3个设备全部编译了一遍，都无法启动
我有点搞不太懂设备树要怎么添加，我看了一篇文章说好想要修改openwrt内核，不知道是不是这样子？
https://openwrt.org/docs/guide-developer/adding_new_device
但是内核修改我没弄过，估计很难。

**Comment by kingo132** [comment]
> 理论上是可以的啊，你确定设备树配置正确，串口中终端设置是uart应该就可以启动的 发送自 Windows 10 版邮件应用 发件人: kingo 发送时间: 2021年2月17日 上午 11:01 收件人: peng-zhihui/Project-Quantum 抄送: Subscribed 主题: [peng-zhihui/Project-Quantum] 求quark-n可以用的openwrt固件 (#23) 我尝试了openwrt官方的OrangePi PC (H3)、BananaPi M2、Orange Pi Plus (H3)固件，都无法启动。 自己按照硬件参数编译了三四次，也没有成功。 求作者出个openwrt固件，或者编译openwrt的参数配置。 希望可以支持openwrt，希望quark-n越来越好，谢谢作者。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

感谢稚晖君，我已经成功编译了最新版本的FriendlyWrt，而且在quark-n上运行成功了，一切正常，只是没有无线网卡驱动。
然后我尝试了一下openwrt里面内置的rtl8xxxu驱动，试了半天也没法驱动这个rtl8723bu网卡，dmesg里总是输出wlan0 is not ready。
然后我又尝试着移植这个驱动（https://github.com/lwfinger/rtl8188eu/）到FriendlyWrt的固件里面，经过一天的折腾，驱动总算是编译成功了，然而加载这个编译好的驱动，系统只提示加载失败，没有输出任何日志，哪怕我把驱动代码里的所有debug选项全部打开，都没有任何信息输出。
`
root@FriendlyWrt:~# modinfo rtl8723bu
module:		/lib/modules/4.14.111/rtl8723bu.ko
license:	GPL
depends:	
root@FriendlyWrt:~# modprobe rtl8723bu
1 module could not be probed
- rtl8723bu
root@FriendlyWrt:~# insmod /lib/modules/4.14.111/rtl8723bu.ko 
failed to insert /lib/modules/4.14.111/rtl8723bu.ko
root@FriendlyWrt:~# dmesg | tail -n 10
[   52.119451] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[ 1414.964224] lib80211: common routines for IEEE802.11 drivers
[ 1414.969956] lib80211_crypt: registered algorithm 'NULL'
[ 2335.376418] r8152 4-1.4:1.0 eth0: carrier off
[ 2476.624544] r8152 4-1.4:1.0 eth0: carrier on
[ 2800.984602] lib80211_crypt: unregistered algorithm 'NULL'
[ 2802.417431] lib80211: common routines for IEEE802.11 drivers
[ 2802.423186] lib80211_crypt: registered algorithm 'NULL'
[ 3869.761974] kmodloader: loading kernel modules from /etc/modules.d/*
[ 3869.781967] kmodloader: done loading kernel modules from /etc/modules.d/*
root@FriendlyWrt:~# 
`
然后我又折腾了半天，修改了很多编译选项，还是老样子。
感觉没思路了，哎，这太难了。。。

**Comment by peng-zhihui** [comment]
去我GitHub的仓库里有内核源码，把相关源码移到你的内核里编译就行了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: kingo <notifications@github.com&gt;
发送时间: 2021年2月18日 13:25
收件人: peng-zhihui/Project-Quantum <Project-Quantum@noreply.github.com&gt;
抄送: 稚晖 <593245898@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[peng-zhihui/Project-Quantum] 求quark-n可以用的openwrt固件 (#23)





  
理论上是可以的啊，你确定设备树配置正确，串口中终端设置是uart应该就可以启动的 发送自 Windows 10 版邮件应用 发件人: kingo 发送时间: 2021年2月17日 上午 11:01 收件人: peng-zhihui/Project-Quantum 抄送: Subscribed 主题: [peng-zhihui/Project-Quantum] 求quark-n可以用的openwrt固件 (#23) 我尝试了openwrt官方的OrangePi PC (H3)、BananaPi M2、Orange Pi Plus (H3)固件，都无法启动。 自己按照硬件参数编译了三四次，也没有成功。 求作者出个openwrt固件，或者编译openwrt的参数配置。 希望可以支持openwrt，希望quark-n越来越好，谢谢作者。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
感谢稚晖君，我已经成功编译了最新版本的FriendlyWrt，而且在quark-n上运行成功了，一切正常，只是没有无线网卡驱动。
 然后我尝试了一下openwrt里面内置的rtl8xxxu驱动，试了半天也没法驱动这个rtl8723bu网卡，dmesg里总是输出wlan0 is not ready。
 然后我又尝试着移植这个驱动（https://github.com/lwfinger/rtl8188eu/）到FriendlyWrt的固件里面，经过一天的折腾，驱动总算是编译成功了，然而加载这个编译好的驱动，系统只提示加载失败，没有输出任何日志，哪怕我把驱动代码里的所有debug选项全部打开，都没有任何信息输出。
 `
 root@FriendlyWrt:# modinfo rtl8723bu
 module:/lib/modules/4.14.111/rtl8723bu.ko
 license:GPL
 depends:
 root@FriendlyWrt:# modprobe rtl8723bu
 1 module could not be probed
  
rtl8723bu
 root@FriendlyWrt:# insmod /lib/modules/4.14.111/rtl8723bu.ko
 failed to insert /lib/modules/4.14.111/rtl8723bu.ko
 root@FriendlyWrt:# dmesg | tail -n 10
 [   52.119451] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
 [ 1414.964224] lib80211: common routines for IEEE802.11 drivers
 [ 1414.969956] lib80211_crypt: registered algorithm 'NULL'
 [ 2335.376418] r8152 4-1.4:1.0 eth0: carrier off
 [ 2476.624544] r8152 4-1.4:1.0 eth0: carrier on
 [ 2800.984602] lib80211_crypt: unregistered algorithm 'NULL'
 [ 2802.417431] lib80211: common routines for IEEE802.11 drivers
 [ 2802.423186] lib80211_crypt: registered algorithm 'NULL'
 [ 3869.761974] kmodloader: loading kernel modules from /etc/modules.d/*
 [ 3869.781967] kmodloader: done loading kernel modules from /etc/modules.d/*
 root@FriendlyWrt:~#
 `
 然后我又折腾了半天，修改了很多编译选项，还是老样子。
 感觉没思路了，哎，这太难了。。。

**Comment by kingo132** [comment]
> 去我GitHub的仓库里有内核源码，把相关源码移到你的内核里编译就行了 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: kingo <notifications@github.com&gt; 发送时间: 2021年2月18日 13:25 收件人: peng-zhihui/Project-Quantum <Project-Quantum@noreply.github.com&gt; 抄送: 稚晖 <593245898@qq.com&gt;, Comment <comment@noreply.github.com&gt; 主题: 回复：[peng-zhihui/Project-Quantum] 求quark-n可以用的openwrt固件 (#23) 理论上是可以的啊，你确定设备树配置正确，串口中终端设置是uart应该就可以启动的 发送自 Windows 10 版邮件应用 发件人: kingo 发送时间: 2021年2月17日 上午 11:01 收件人: peng-zhihui/Project-Quantum 抄送: Subscribed 主题: [peng-zhihui/Project-Quantum] 求quark-n可以用的openwrt固件 (#23) 我尝试了openwrt官方的OrangePi PC (H3)、BananaPi M2、Orange Pi Plus (H3)固件，都无法启动。 自己按照硬件参数编译了三四次，也没有成功。 求作者出个openwrt固件，或者编译openwrt的参数配置。 希望可以支持openwrt，希望quark-n越来越好，谢谢作者。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 感谢稚晖君，我已经成功编译了最新版本的FriendlyWrt，而且在quark-n上运行成功了，一切正常，只是没有无线网卡驱动。 然后我尝试了一下openwrt里面内置的rtl8xxxu驱动，试了半天也没法驱动这个rtl8723bu网卡，dmesg里总是输出wlan0 is not ready。 然后我又尝试着移植这个驱动（[https://github.com/lwfinger/rtl8188eu/）到FriendlyWrt的固件里面，经过一天的折腾，驱动总算是编译成功了，然而加载这个编译好的驱动，系统只提示加载失败，没有输出任何日志，哪怕我把驱动代码里的所有debug选项全部打开，都没有任何信息输出。](https://github.com/lwfinger/rtl8188eu/%EF%BC%89%E5%88%B0FriendlyWrt%E7%9A%84%E5%9B%BA%E4%BB%B6%E9%87%8C%E9%9D%A2%EF%BC%8C%E7%BB%8F%E8%BF%87%E4%B8%80%E5%A4%A9%E7%9A%84%E6%8A%98%E8%85%BE%EF%BC%8C%E9%A9%B1%E5%8A%A8%E6%80%BB%E7%AE%97%E6%98%AF%E7%BC%96%E8%AF%91%E6%88%90%E5%8A%9F%E4%BA%86%EF%BC%8C%E7%84%B6%E8%80%8C%E5%8A%A0%E8%BD%BD%E8%BF%99%E4%B8%AA%E7%BC%96%E8%AF%91%E5%A5%BD%E7%9A%84%E9%A9%B1%E5%8A%A8%EF%BC%8C%E7%B3%BB%E7%BB%9F%E5%8F%AA%E6%8F%90%E7%A4%BA%E5%8A%A0%E8%BD%BD%E5%A4%B1%E8%B4%A5%EF%BC%8C%E6%B2%A1%E6%9C%89%E8%BE%93%E5%87%BA%E4%BB%BB%E4%BD%95%E6%97%A5%E5%BF%97%EF%BC%8C%E5%93%AA%E6%80%95%E6%88%91%E6%8A%8A%E9%A9%B1%E5%8A%A8%E4%BB%A3%E7%A0%81%E9%87%8C%E7%9A%84%E6%89%80%E6%9C%89debug%E9%80%89%E9%A1%B9%E5%85%A8%E9%83%A8%E6%89%93%E5%BC%80%EF%BC%8C%E9%83%BD%E6%B2%A1%E6%9C%89%E4%BB%BB%E4%BD%95%E4%BF%A1%E6%81%AF%E8%BE%93%E5%87%BA%E3%80%82) ` root@FriendlyWrt:# modinfo rtl8723bu module:/lib/modules/4.14.111/rtl8723bu.ko license:GPL depends: root@FriendlyWrt:# modprobe rtl8723bu 1 module could not be probed rtl8723bu root@FriendlyWrt:# insmod /lib/modules/4.14.111/rtl8723bu.ko failed to insert /lib/modules/4.14.111/rtl8723bu.ko root@FriendlyWrt:# dmesg | tail -n 10 [ 52.119451] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready [ 1414.964224] lib80211: common routines for IEEE802.11 drivers [ 1414.969956] lib80211_crypt: registered algorithm 'NULL' [ 2335.376418] r8152 4-1.4:1.0 eth0: carrier off [ 2476.624544] r8152 4-1.4:1.0 eth0: carrier on [ 2800.984602] lib80211_crypt: unregistered algorithm 'NULL' [ 2802.417431] lib80211: common routines for IEEE802.11 drivers [ 2802.423186] lib80211_crypt: registered algorithm 'NULL' [ 3869.761974] kmodloader: loading kernel modules from /etc/modules.d/* [ 3869.781967] kmodloader: done loading kernel modules from /etc/modules.d/* root@FriendlyWrt:~# ` 然后我又折腾了半天，修改了很多编译选项，还是老样子。 感觉没思路了，哎，这太难了。。。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

谢谢稚晖君，你的内核源码里的rtl8723bu驱动代码和我发的github仓库地址里的是一样的，我用了你内核里的代码编译了也不行，可能是哪里的编译选项没设置对，我以后再研究了，现在暂时先买个usb无线网卡。
另外我测试了两个usb口分别插千兆网卡，一个做wwan一个做lan，这样在我的500Mbps宽带下面测出了90Mbps的速度，不知道是不是因为usb2.0限制了速度。另外我在linux下用iperf测试了一下这个wifi的速度，大概在30Mbps左右。
然后我想在openwrt下驱动这个tft屏幕，我发现openwrt里面支持一个叫fbtft的驱动，我编译进去了，但是还是屏幕显示不了。
另外我发现了一个nanohat的openwrt的驱动，但是这个nanohat是i2c接口的，我看这个quark小电脑的屏幕说明是spi接口的。
我有点搞不懂了，不知道有没有这个屏幕驱动的相关资料，我好研究一下怎么在openwrt下驱动，谢谢！

**Comment by kingo132** [comment]
经过曲折的过程，终于在openwrt下面移植成功了rtl8723bu驱动，wifi成功进入ap模式，实测上网速度可以达到16～20Mbps，还是受限于内置网卡，速度不太行，希望下次可以升级内置网卡支持5Ghz

**Comment by kingo132** [comment]
而且这个内置wifi好像不是很稳定，有时候会变的很慢或者断线，必须要放到离设备很近速度才能达到20Mbps，不知道上面有没有触点可以焊跟小电线作为天线提高信号什么的，有可能我自己这样焊接实现吗？

**Comment by kingo132** [comment]
我好像发现tf卡会挡wifi的信号，拔掉tf卡用emmc运行系统，Wi-Fi速度可以达到20～30Mbps，拔掉tf卡可以提高一点速度和稳定性

**Comment by kingo132** [comment]
硬件盲不会修改主板，直接怼上一个rtl8812AU迷你usb无线网卡(0bda:0811)，开启5Ghz的AP，上网速度直接蹦到70~80Mbps，这下美滋滋了，全宇宙最小的软路由诞生了✌️

**Comment by kingo132** [comment]
我做了一个quark电脑可用的openwrt固件，需要的可以在这里下载：https://github.com/kingo132/quark-n-openwrt

**Comment by peng-zhihui** [comment]
很棒，后面我可以把你的仓库作为模块引入哈



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: kingo <notifications@github.com&gt;
发送时间: 2021年3月1日 12:49
收件人: peng-zhihui/Project-Quantum <Project-Quantum@noreply.github.com&gt;
抄送: 稚晖 <593245898@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[peng-zhihui/Project-Quantum] 求quark-n可以用的openwrt固件 (#23)





 
我做了一个quark电脑可用的openwrt固件，需要的可以在这里下载：https://github.com/kingo132/quark-n-openwrt

**Comment by kingo132** [comment]
> 很棒，后面我可以把你的仓库作为模块引入哈 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: kingo <notifications@github.com&gt; 发送时间: 2021年3月1日 12:49 收件人: peng-zhihui/Project-Quantum <Project-Quantum@noreply.github.com&gt; 抄送: 稚晖 <593245898@qq.com&gt;, Comment <comment@noreply.github.com&gt; 主题: 回复：[peng-zhihui/Project-Quantum] 求quark-n可以用的openwrt固件 (#23) 我做了一个quark电脑可用的openwrt固件，需要的可以在这里下载：https://github.com/kingo132/quark-n-openwrt — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by kingo132** [comment]
> 很棒，后面我可以把你的仓库作为模块引入哈 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: kingo <notifications@github.com&gt; 发送时间: 2021年3月1日 12:49 收件人: peng-zhihui/Project-Quantum <Project-Quantum@noreply.github.com&gt; 抄送: 稚晖 <593245898@qq.com&gt;, Comment <comment@noreply.github.com&gt; 主题: 回复：[peng-zhihui/Project-Quantum] 求quark-n可以用的openwrt固件 (#23) 我做了一个quark电脑可用的openwrt固件，需要的可以在这里下载：https://github.com/kingo132/quark-n-openwrt — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

谢谢！

**Comment by whatt12** [comment]
请问quark-n怎样擦除emmc中的系统啊
